#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
build_cat1_mcq_from_event_stream.py

Generate Cat1 Multiple Choice questions from visit event_stream.

Outputs (JSONL):
- one line per question

Question types:
- T3-N: Next Action (always)
- T3-A: Parameter question if GT (labs/imaging/micro/procedure/medication)
- T3-D: Discharge Yes/No near discharge time

Distractors:
- ALL distractors generated by LLM, given full history up to current time + GT.
- Heuristic "preference" hints are passed to LLM (but LLM decides final options).

Labs parameter GT:
- If you provide --indicator_panel_map (indicator_key -> panel_name),
  we infer panels for a lab event by voting over its items.
- indicator_key uses composite key: name||fluid||unit_norm (recommended).

Time-window GT merge:
- For T3-A (labs/imaging/micro/medication), collect all corresponding events in (t, t+24h],
  produce gt_list=[{"value":..., "delta_hours":..., "weight":...}, ...]
  with exp decay weight where 0h->1.0, 24h->0.01.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import random
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
from collections import Counter, defaultdict

from tqdm import tqdm
from util.logUtil import setup_logger
logger = setup_logger()

from tasks.agentic_decision.tools import *

# --------- question objects ----------
@dataclass
class Question:
    qid: str
    visit_id: str
    hadm_id: Any
    t_index: int
    timestamp: str
    qtype: str
    question: str
    options: List[Any]
    answer: Dict[str, float]
    meta: Dict[str, Any]

def make_qid(patient_id: str, visit_id: str, t_index: int, qtype: str, local_i: int) -> str:
    return f"{visit_id}-T{t_index:04d}-{qtype}-{local_i}"

# --------- future-window gt list ----------
def collect_future_events(
    events: List[Dict[str, Any]],
    t0: datetime,
    horizon_h: float,
    match_action: str,
) -> List[Tuple[datetime, Dict[str, Any]]]:
    t1 = t0 + timedelta(hours=horizon_h)
    out = []
    for ev in events:
        ts = parse_time(ev["timestamp"])
        if ev["type"].lower() == "procedure":
            # since procedure only has day-level timestamp, we consider it matches if it's on the same day as t0 or within horizon
            if ts.date() < t0.date():
                continue
            if ts.date() > t1.date():
                continue
        else:
            if ts <= t0:
                continue
            if ts > t1:
                continue
        act = gt_action_from_event(ev)
        if act == match_action:
            out.append((ts, ev))
    out.sort(key=lambda x: x[0])
    return out

# --------- builders ----------
def build_T3N(
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    gt_action: str,
    out_options_k: int,
) -> Question:
    history = build_history(visit, t_cur)
    stem = "Which of the next step is most appropriate?"

    options = random.sample([a for a in ACTIONS if a != gt_action], out_options_k - 1) + [gt_action]
    random.shuffle(options)
    # shuffle but keep deterministic-ish: put GT random? here keep last to simplify
    q = Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-N", 0),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-N",
        question=stem,
        options=options,
        answer={gt_action: 1.0},
        meta={"history": history, "gt_action": gt_action},
    )
    return q

def build_T3A_labs(
    llm: LLMUtil,
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    indicator_panel_map: Optional[Dict[str, str]],
    out_options_k: int,
) -> Optional[Question]:
    # merge all lab events within 24h after current time (including next)
    future = collect_future_events(events, t_cur, 24.0, "order_labs")
    if not future:
        return None

    gt_list = []
    chosen_panel = None
    debug_list = []

    for ts, ev in future:
        panel, dbg = infer_lab_panel_for_event(llm, ev, indicator_panel_map)
        debug_list.append({"timestamp": ev["timestamp"], "panel": panel, "debug": dbg})
        if not panel:
            continue
        dh = (ts - t_cur).total_seconds() / 3600.0
        gt_list.append({"value": panel, "delta_hours": dh, "weight": decay_weight(dh)})

    if not gt_list:
        return None

    # main GT: earliest panel
    chosen_panel = gt_list[0]["value"]
    history = build_history(visit, t_cur)
    stem = f"Which {len(chosen_panel)} lab panels are most appropriate next?"

    # LLM generate irrelevant panel names
    forbid = chosen_panel
    hint = "Generate common but irrelevant lab orders/panels that do NOT match GT."

    if isinstance(chosen_panel, list) and len(chosen_panel) < out_options_k:
        distractors = llm_generate_options(
            llm,
            qtype="T3-A-labs",
            stem=stem,
            gt={"panel": chosen_panel, "gt_list": gt_list},
            history=history,
            n_options=out_options_k - len(chosen_panel),
            forbid=forbid,
            preference_hint=hint,
        )
        # backfill with generic negatives if needed
        while len(distractors) < out_options_k - 1:
            distractors.append(f"Unrelated Lab Order {len(distractors)+1}")

        options = distractors[: out_options_k - 1] + chosen_panel
    elif len(chosen_panel) >= out_options_k:
        options = chosen_panel[:out_options_k]  # too many GT panels, just take some
        chosen_panel = {p: 1.0 for p in options}
    else:
        logger.warning(f"GT panel is not a list for event at {events[t_index]['timestamp']}. Got: {chosen_panel}. Skipping question.")
        return None
    random.shuffle(options)  
    answer = {}
    for p in chosen_panel:
        answer[p] = 1.0 / len(chosen_panel)
        
    return Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-A", 0),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-A",
        question=stem,
        options=options,
        answer=answer,
        meta={
            "subtype": "labs",
            "history": history,
            "gt_list": gt_list,
            "gt_primary": chosen_panel,
            "debug": debug_list,
        },
    )

def build_T3A_imaging(
    llm: LLMUtil,
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    out_options_k: int,
) -> Optional[Question]:
    future = collect_future_events(events, t_cur, 24.0, "order_imaging")
    if not future:
        return None

    history = build_history(visit, t_cur)

    gt_list = []
    debug = []
    for ts, ev in future:
        lab = infer_imaging_param_for_event(llm, ev, history_messages=None)
        # normalize to a single string option
        modality = norm(lab.get("modality") or "other").lower()
        target = norm(lab.get("target") or "")
        value = f"{modality.upper()} {target}".strip()
        dh = (ts - t_cur).total_seconds() / 3600.0
        gt_list.append({"value": value, "delta_hours": dh, "weight": decay_weight(dh)})
        debug.append({"timestamp": ev["timestamp"], "parsed": lab})

    if not gt_list:
        return None

    chosen, weight = gt_list[0]["value"], gt_list[0]["weight"]
    answer = {chosen: 1.0}
    stem = "Which imaging order is most appropriate next?"
    forbid = [chosen]
    for item in gt_list:
        forbid.append(item["value"])
        answer[item["value"]] = item["weight"] / weight  # if multiple GT, can give partial credit
    hint = "Generate imaging orders that are irrelevant to GT. Prefer same body part different modality, or same modality different body part."

    distractors = llm_generate_options(
        llm=llm,
        qtype="T3-A-imaging",
        stem=stem,
        gt={"imaging": chosen, "gt_list": gt_list},
        history=history,
        n_options=out_options_k - len(gt_list),
        forbid=forbid,
        preference_hint=hint,
    )
    while len(distractors) < out_options_k - len(gt_list):
        distractors.append(f"XR Unrelated Part {len(distractors)+1}")

    options = distractors[: out_options_k - len(gt_list)] + list(answer.keys())
    random.shuffle(options)
    
    return Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-A", 1),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-A",
        question=stem,
        options=options,
        answer=answer,
        meta={"subtype": "imaging", "history": history, "gt_list": gt_list, "gt_primary": chosen, "debug": debug},
    )

def build_T3A_micro(
    llm: LLMUtil,
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    out_options_k: int,
) -> Optional[Question]:
    future = collect_future_events(events, t_cur, 24.0, "order_microbiology")
    if not future:
        return None

    history = build_history(visit, t_cur)

    gt_list = []
    debug = []
    for ts, ev in future:
        # p = infer_micro_param_for_event(ev)
        p = ev["specimen"]
        specimen = norm(p.get("spec_type") or "")
        test = norm(p.get("test_name") or "culture")
        value = f"{specimen} {test}".strip()
        dh = (ts - t_cur).total_seconds() / 3600.0
        gt_list.append({"value": value, "delta_hours": dh, "weight": decay_weight(dh)})
        debug.append({"timestamp": ev["timestamp"], "parsed": p})

    if not gt_list:
        return None

    chosen, weight = gt_list[0]["value"], gt_list[0]["weight"]
    answer = {chosen: 1.0}
    stem = "Which microbiology test is most appropriate next?"
    forbid = [chosen]
    hint = "Generate microbiology orders that are irrelevant to GT. Prefer different specimen or different test type."
    for item in gt_list:
        forbid.append(item["value"])
        answer[item["value"]] = item["weight"] / weight  # if multiple GT, can give partial credit

    distractors = llm_generate_options(
        llm=llm,
        qtype="T3-A-micro",
        stem=stem,
        gt={"micro": chosen, "gt_list": gt_list},
        history=history,
        n_options=out_options_k - len(gt_list),
        forbid=forbid,
        preference_hint=hint,
    )
    while len(distractors) < out_options_k - len(gt_list):
        distractors.append(f"Urine culture (irrelevant) {len(distractors)+1}")

    options = distractors[: out_options_k - len(gt_list)] + list(answer.keys())
    random.shuffle(options)

    return Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-A", 2),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-A",
        question=stem,
        options=options,
        answer=answer,
        meta={"subtype": "micro", "history": history, "gt_list": gt_list, "gt_primary": answer, "debug": debug},
    )

def build_T3A_medication(
    llm: LLMUtil,
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    out_options_k: int,
) -> Optional[Question]:
    future = collect_future_events(events, t_cur, 24.0, "medication")
    if not future:
        return None

    history = build_history(visit, t_cur)

    # choose earliest med in earliest medication event as primary GT
    ts0, ev0 = future[0]
    mp = infer_med_param_for_event(ev0)
    meds = mp.get("meds", []) or []
    if not meds:
        return None
    
    primary_drugs = []
    for d in meds:
        drug = norm(d.get("drug") or "")
        if drug:
            primary_drugs.append(drug)
    result = {tuple(primary_drugs): 1.0}  # if multiple meds, can give partial credit to any subset; for simplicity we just give full credit to all as a set
    # GT list can include multiple meds in 24h window (topk evaluation)
    gt_list = []
    debug = []
    primary_weight = decay_weight((ts0 - t_cur).total_seconds() / 3600.0)
    for ts, ev in future:
        mp2 = infer_med_param_for_event(ev)
        secondary_drugs = []
        dh = (ts - t_cur).total_seconds() / 3600.0
        decayed_weight = decay_weight(dh)
        for m in mp2.get("meds", []) or []:
            gt_list.append({"value": m["drug"], "delta_hours": dh, "weight": decayed_weight})
            secondary_drugs.append(m["drug"])
        result[tuple(secondary_drugs)] = decayed_weight / primary_weight  # partial credit for secondary GT meds
        debug.append({"timestamp": ev["timestamp"], "meds": mp2.get("meds", [])})
        
    if len(primary_drugs) == 0 or len(primary_drugs) > out_options_k:
        logger.warning(f"GT medication is empty or too large for event at {events[t_index]['timestamp']}. Got: {primary_drugs}. Skipping question.")
        return None
    
    stem = f"Which {len(primary_drugs)} medications are most appropriate next?"
    future_drug = []
    for item in gt_list:
        drug = item["value"]
        if drug not in primary_drugs:
            future_drug.append(drug)
    forbid = primary_drugs + future_drug  # forbid primary GT + other GT meds in 24h window
    hint = "Generate medications that are plausible but irrelevant to the current GT and history. Avoid near-duplicate drug names."

    distractors = llm_generate_options(
        llm=llm,
        qtype="T3-A",
        stem=stem,
        gt={"drug": primary_drugs, "gt_list": gt_list},
        history=history,
        n_options=out_options_k - len(forbid),
        forbid=forbid,
        preference_hint=hint,
    )
    while len(distractors) < out_options_k - len(forbid):
        distractors.append(f"Unrelated Drug {len(distractors)+1}")

    options = distractors[: out_options_k - len(forbid)] + forbid
    if len(options) > out_options_k:
        options = options[:out_options_k]  # in case GT meds exceed k, just take some
    random.shuffle(options)
    answer = {}
    for t, w in result.items():
        for drug in t:
            if drug in forbid:
                answer[drug] = w/len(t)  # partial credit for GT meds
    
    return Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-M", 0),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-M",
        question=stem,
        options=options,
        answer=answer,
        meta={"history": history, "gt_list": gt_list, "gt_primary": primary_drugs, "debug": answer},
    )
    
def pick_tcur_for_discharge(
    rng: random.Random,
    events: List[Dict[str, Any]],
    discharge_time: datetime,
    X_hours: float,
    yes_ratio: float,
    min_gap_h: float = 0.0,
    no_margin_h: float = 6.0,
    within_h: float = 72.0,
) -> Optional[Tuple[int, datetime]]:
    """
    从事件时间戳中挑一个作为 T3-D 的 t_cur（返回事件 index + t_cur）。
    - 优先挑“靠近出院”的 event（上下文自然）
    - yes_ratio 控制 Yes/No 的采样比例
    Yes 区间： (discharge_time - X_hours, discharge_time - min_gap_h]
    No  区间： (discharge_time - (X_hours + no_margin_h), discharge_time - X_hours)
    并且只在最后 within_h 小时内采样（减少重复、提高相关性）
    """
    if not events:
        return None

    # events 已经按 timestamp 排序（你在 generate_questions_for_visit 里排过）
    # 构建候选：取 <= discharge_time 的事件点，且在出院前 within_h 小时内
    candidates: List[Tuple[int, datetime]] = []
    t_min = discharge_time - timedelta(hours=within_h)
    for i, ev in enumerate(events):
        t = parse_time(ev["timestamp"])
        if t > discharge_time:
            break
        if t < t_min:
            continue
        candidates.append((i, t))

    if not candidates:
        return None

    # 划分 Yes / No 候选
    yes_lo = discharge_time - timedelta(hours=X_hours)
    yes_hi = discharge_time - timedelta(hours=min_gap_h)
    no_lo = discharge_time - timedelta(hours=X_hours + no_margin_h)
    no_hi = discharge_time - timedelta(hours=X_hours)

    yes_cands = [(i, t) for (i, t) in candidates if (t > yes_lo and t <= yes_hi)]
    no_cands  = [(i, t) for (i, t) in candidates if (t > no_lo  and t <= no_hi)]

    want_yes = rng.random() < yes_ratio
    pool = yes_cands if want_yes else no_cands
    if not pool:
        # fallback：如果目标池为空，退化到另一个池；再不行就随便挑最后一段
        pool = no_cands if want_yes else yes_cands
    if not pool:
        pool = candidates[-min(len(candidates), 50):]  # 最后 50 个事件里挑

    return rng.choice(pool)

def build_T3D_discharge(
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    discharge_time: Optional[datetime],
    X_hours: float,
    out_options_k: int = 2,
    seed: int = 42,
) -> Optional[Question]:
    if discharge_time is None:
        return None
    # label: Yes if discharge within X hours after t_cur
    yes = (discharge_time - t_cur).total_seconds() / 3600.0 <= X_hours
    gt = "Yes" if yes else "No"

    history = build_history(visit, t_cur)
    stem = f"Should the patient be discharged within {X_hours:.0f}h?"

    options = ["Yes", "No"]
    return Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-D", 0),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-D",
        question=stem,
        options=options,
        answer={gt: 1.0},
        meta={"history": history, "discharge_time": discharge_time.strftime("%Y-%m-%d %H:%M:%S"), "X_hours": X_hours},
    )

def build_T3A_procedure(
    llm: LLMUtil,
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    out_options_k: int,
) -> Optional["Question"]:

    future = collect_future_events(events, t_cur, 24.0, "perform_procedure")
    if not future:
        return None

    history = build_history(visit, t_cur)

    # group by exact timestamp: many procedures share same ts
    future_groups = group_future_by_timestamp(future)
    if not future_groups:
        return None

    # primary group: earliest timestamp bucket
    ts0, evs0 = future_groups[0]

    primary_procs: List[str] = []
    for ev in evs0:
        name = norm(ev.get("name") or "")
        if name:
            primary_procs.append(name)

    # dedup keep order
    seen = set()
    primary_procs = [x for x in primary_procs if not (x in seen or seen.add(x))]

    if len(primary_procs) == 0 or len(primary_procs) > out_options_k:
        logger.warning(
            f"GT procedure is empty or too large at {events[t_index]['timestamp']}. "
            f"Got {len(primary_procs)}: {primary_procs[:5]}"
        )
        return None

    # scoring sets
    result = {tuple(primary_procs): 1.0}

    gt_list: List[Dict[str, Any]] = []
    debug: List[Dict[str, Any]] = []

    primary_weight = decay_weight((ts0 - t_cur).total_seconds() / 3600.0)

    for ts, evs in future_groups:
        dh = (ts - t_cur).total_seconds() / 3600.0
        w = decay_weight(dh)

        bucket = []
        for ev in evs:
            name = norm(ev.get("name") or "")
            if not name:
                continue
            gt_list.append({"value": name, "delta_hours": dh, "weight": w})
            bucket.append(name)

        # dedup
        seen2 = set()
        bucket = [x for x in bucket if not (x in seen2 or seen2.add(x))]

        if bucket:
            result[tuple(bucket)] = w / primary_weight

        debug.append({"timestamp": evs[0].get("timestamp"), "procedures": bucket})

    stem = f"Which {len(primary_procs)} procedures are most appropriate next?"

    # forbid = primary + other GT procedures in 24h window
    future_proc = []
    for item in gt_list:
        p = norm(item["value"])
        if p and p not in primary_procs:
            future_proc.append(p)

    forbid = primary_procs + future_proc

    n_distractors = out_options_k - len(forbid)
    if n_distractors < 0:
        n_distractors = 0

    hint = "Generate procedures that are plausible but irrelevant to the current GT and history. Avoid near-duplicate procedure names."

    distractors = llm_generate_options(
        llm=llm,
        qtype="T3-A-procedure",
        stem=stem,
        gt={"procedure": primary_procs, "gt_list": gt_list},
        history=history,
        n_options=n_distractors,
        forbid=forbid,
        preference_hint=hint,
    )
    while len(distractors) < n_distractors:
        distractors.append(f"Unrelated Procedure {len(distractors)+1}")

    options = distractors[:n_distractors] + forbid
    if len(options) > out_options_k:
        options = options[:out_options_k]
    random.shuffle(options)

    answer: Dict[str, float] = {}
    for t_set, w in result.items():
        for proc in t_set:
            if proc in forbid:
                answer[proc] = max(answer.get(proc, 0.0), w / max(len(t_set), 1))

    return Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-P", 0),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-P",
        question=stem,
        options=options,
        answer=answer,
        meta={
            "subtype": "procedure",
            "history": history,
            "gt_list": gt_list,
            "gt_primary": primary_procs,
            "debug": debug,
        },
    )

# --------- main pipeline ----------



def sample_decision_points(events: List[Dict[str, Any]], n_points: int, seed: int, visit_key: str) -> List[int]:
    """
    Sample n_points indices i as decision points in this visit.
    Constraint: i must allow GT = events[i+1], so i in [0, len(events)-2].
    We also avoid picking indices where next event cannot be mapped to GT action.
    """
    if len(events) < 2:
        return []

    # deterministic RNG per visit
    rng = random.Random(f"{seed}::{visit_key}")

    candidates = []
    for i in range(len(events) - 1):
        nxt = events[i + 1]
        if gt_action_from_event(nxt):
            candidates.append(i)

    if not candidates:
        return []

    if len(candidates) <= n_points:
        return sorted(candidates)

    return sorted(rng.sample(candidates, k=n_points))

def generate_questions_for_visit(
    llm: LLMUtil,
    patient_id: str,
    visit: Dict[str, Any],
    indicator_panel_map: Optional[Dict[str, str]],
    k_action: int,
    k_param: int,
    k_med: int,
    enable_discharge_q: bool,
    discharge_Xh: float,
    discharge_only_within_h: float,
    discharge_yes_ratio: float,
    discharge_min_gap_h: float,
    discharge_no_margin_h: float,
    discharge_sample_k: int,
    seed: int = 42,
) -> List[Dict[str, Any]]:
    events = list(visit.get("event_stream", []) or [])
    if len(events) < 2:
        return []

    # sort by timestamp
    events.sort(key=lambda e: parse_time(e["timestamp"]))

    discharge_time = None
    try:
        dt = visit.get("discharge_info", {}).get("discharge_time")
        if dt:
            discharge_time = parse_time(dt)
    except Exception:
        discharge_time = None

    out: List[Question] = []

    # ---- sample 2 decision points per visit ----
    visit_key = f"{patient_id}::{visit.get('visit_id')}::{visit.get('hadm_id')}"
    decision_points = sample_decision_points(events, n_points=2, seed=seed, visit_key=visit_key)
    logger.info(f"Visit {visit_key}: sampled decision points at indices {decision_points} / {len(events)-1}")
    
    for i in decision_points:
        cur = events[i]
        nxt = events[i + 1]
        t_cur = parse_time(cur["timestamp"])

        gt_act = gt_action_from_event(nxt)
        if not gt_act:
            continue

        # ---- T3-N (always) ----
        out.append(build_T3N(patient_id, visit, events, i, t_cur, gt_act, k_action))

        # ---- 1 extra question max by default (param or med). You can allow 2 if you want. ----
        if gt_act == "order_labs":
            q = build_T3A_labs(llm, patient_id, visit, events, i, t_cur, indicator_panel_map, k_param)
            if q: out.append(q)
        elif gt_act == "order_imaging":
            q = build_T3A_imaging(llm, patient_id, visit, events, i, t_cur, k_param)
            if q: out.append(q)
        elif gt_act == "order_microbiology":
            q = build_T3A_micro(llm, patient_id, visit, events, i, t_cur, k_param)
            if q: out.append(q)
        elif gt_act == "medication":
            q = build_T3A_medication(llm, patient_id, visit, events, i, t_cur, k_med)
            if q: out.append(q)
        elif gt_act == "perform_procedure":
            q = build_T3A_procedure(llm, patient_id, visit, events, i, t_cur, k_param)
            if q: out.append(q)
        else:
            logger.warning(f"GT action {gt_act} at index {i+1} does not match any known action types. Skipping param question.")
            continue

    # ---- T3-D: independently sample near-discharge timepoints to control YES ratio ----
    if enable_discharge_q and discharge_time is not None and discharge_sample_k > 0:
        # visit-level deterministic RNG
        rng_d = random.Random(f"{seed}::T3D::{visit_key}")

        for _ in range(discharge_sample_k):
            picked = pick_tcur_for_discharge(
                rng=rng_d,
                events=events,
                discharge_time=discharge_time,
                X_hours=discharge_Xh,
                yes_ratio=discharge_yes_ratio,
                min_gap_h=discharge_min_gap_h,
                no_margin_h=discharge_no_margin_h,
                within_h=discharge_only_within_h,
            )
            if not picked:
                continue
            i_pick, t_pick = picked

            qd = build_T3D_discharge(
                patient_id=patient_id,
                visit=visit,
                events=events,
                t_index=i_pick,
                t_cur=t_pick,
                discharge_time=discharge_time,
                X_hours=discharge_Xh,
                out_options_k=2,
            )
            if qd:
                out.append(qd)


    # serialize
    return [q.__dict__ for q in out]

def load_indicator_panel_map(path: Optional[str]) -> Optional[Dict[str, str]]:
    if not path:
        return None
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(p)
    return json.loads(p.read_text(encoding="utf-8"))

def write_questions_jsonl(patient_out_path: Path, questions: List[Dict[str, Any]]) -> int:
    if not questions:
        return 0
    patient_out_path.parent.mkdir(parents=True, exist_ok=True)
    with patient_out_path.open("a", encoding="utf-8") as fw:
        for q in questions:
            fw.write(json.dumps(q, ensure_ascii=False) + "\n")
    return len(questions)

from concurrent.futures import ProcessPoolExecutor, as_completed
import os

def process_one_patient(fp_str: str, cfg_dict: Dict[str, Any])\
    -> Tuple[str, int, Dict[str, Dict[str, int]]]:
    """
    Worker: process one patient file and write its jsonl.
    Return: (patient_id, n_questions_written)
    """
    # IMPORTANT: init LLM inside worker
    llm = LLMUtil()

    fp = Path(fp_str)
    obj = json.loads(fp.read_text(encoding="utf-8"))
    patient_id = obj.get("patient_info", {}).get("patient_id") or fp.stem

    out_path = Path(cfg_dict["OUTPUT_PATH"])
    out_path.mkdir(parents=True, exist_ok=True)
    patient_out = out_path / f"{patient_id}.jsonl"

    # load indicator_panel_map (read-only) inside worker
    ind_map_path = cfg_dict.get("INDICATOR_PANEL_MAP")
    indicator_panel_map = load_indicator_panel_map(ind_map_path) if ind_map_path else None

    total_written = 0
    visits = (obj.get("visits", []) or [])
    start_visit = int(cfg_dict.get("AGENT_TASK_STARTING_VISIT", 0))
    visits = visits[start_visit:]

    for visit in visits:
        try:
            qs = generate_questions_for_visit(
                llm=llm,
                patient_id=patient_id,
                visit=visit,
                indicator_panel_map=indicator_panel_map,
                k_action=int(cfg_dict["K_ACTION"]),
                k_param=int(cfg_dict["K_PARAM"]),
                k_med=int(cfg_dict["K_MED"]),
                enable_discharge_q=bool(cfg_dict["ENABLE_DISCHARGE_Q"]),
                discharge_Xh=float(cfg_dict["DISCHARGE_XH"]),
                discharge_only_within_h=float(cfg_dict["DISCHARGE_ONLY_WITHIN_H"]),
                seed=int(cfg_dict["RANDOM_SEED"]),
                discharge_yes_ratio=float(cfg_dict.get("DISCHARGE_YES_RATIO", 0.7)),
                discharge_min_gap_h=float(cfg_dict.get("DISCHARGE_MIN_GAP_H", 0.0)),
                discharge_no_margin_h=float(cfg_dict.get("DISCHARGE_NO_MARGIN_H", 6.0)),
                discharge_sample_k=int(cfg_dict.get("DISCHARGE_SAMPLE_K", 1)),
            )
            total_written += write_questions_jsonl(patient_out, qs)
        except Exception as e:
            logger.error(f"Error processing patient {patient_id} visit {visit.get('visit_id')}: {e}")
            continue
    logger.info(f"Patient {patient_id}: wrote {total_written} questions to {patient_out}")
    logger.info(f"Token usage: {json.dumps(llm.get_token_usage(), ensure_ascii=False, indent=2)}")

    return patient_id, total_written, llm.get_token_usage()


def main():
    from config import AgentQaGenConfig
    cfg = AgentQaGenConfig()

    in_dir = Path(cfg.INPUT_DIR)
    out_dir = Path(cfg.OUTPUT_PATH)
    out_dir.mkdir(parents=True, exist_ok=True)
    global_token_usage = {
        "prompt_tokens": 0,
        "completion_tokens": 0,
        "total_tokens": 0,
    }
    files = list(iter_json_files(in_dir))
    if cfg.DEMO_MODE:
        files = files[: cfg.DEMO_N]

    # pack cfg to dict (so it can be pickled)
    cfg_dict = {
        "INPUT_DIR": str(cfg.INPUT_DIR),
        "OUTPUT_PATH": str(cfg.OUTPUT_PATH),
        "INDICATOR_PANEL_MAP": getattr(cfg, "INDICATOR_PANEL_MAP", None),
        "K_ACTION": cfg.K_ACTION,
        "K_PARAM": cfg.K_PARAM,
        "K_MED": cfg.K_MED,
        "ENABLE_DISCHARGE_Q": cfg.ENABLE_DISCHARGE_Q,
        "DISCHARGE_XH": cfg.DISCHARGE_XH,
        "DISCHARGE_ONLY_WITHIN_H": cfg.DISCHARGE_ONLY_WITHIN_H,
        "RANDOM_SEED": cfg.RANDOM_SEED,
        "AGENT_TASK_STARTING_VISIT": getattr(cfg, "AGENT_TASK_STARTING_VISIT", 0),
    }

    max_workers = getattr(cfg, "MAX_WORKERS", None) or min(8, os.cpu_count() or 4)

    total_q = 0
    total_patients = 0

    with ProcessPoolExecutor(max_workers=max_workers) as ex:
        futs = [ex.submit(process_one_patient, str(fp), cfg_dict) for fp in files]
        for fut in tqdm(as_completed(futs), total=len(futs), desc="Patients"):
            pid, n, usage = fut.result()
            if n > 0:
                total_patients += 1
                total_q += n
                for k in global_token_usage.keys():
                    global_token_usage[k] += (usage.get("chat",{})).get(k, 0)
    
    # for fp in tqdm(files, desc="Patients"):
    #     pid, n, usage = process_one_patient(str(fp), cfg_dict)
    #     if n > 0:
    #         total_patients += 1
    #         total_q += n
    #         for k in global_token_usage.keys():
    #             global_token_usage[k] += (usage.get("chat",{})).get(k, 0)

    logger.success(f"Wrote {total_q} questions for {total_patients} patients into folder: {cfg.OUTPUT_PATH}")
    logger.info(f"Global token usage: {json.dumps(global_token_usage, ensure_ascii=False, indent=2)}")
if __name__ == "__main__":
    main()