#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
build_cat1_mcq_from_event_stream.py

Generate Cat1 Multiple Choice questions from visit event_stream.

Outputs (JSONL):
- one line per question

Question types:
- T3-N: Next Action (always)
- T3-A: Parameter question if GT is order_xxx (labs/imaging/micro/procedure)
- T3-M: Medication question if GT is medication
- T3-D: Discharge Yes/No near discharge time

Distractors:
- ALL distractors generated by LLM, given full history up to current time + GT.
- Heuristic "preference" hints are passed to LLM (but LLM decides final options).

Labs parameter GT:
- If you provide --indicator_panel_map (indicator_key -> panel_name),
  we infer panels for a lab event by voting over its items.
- indicator_key uses composite key: name||fluid||unit_norm (recommended).

Time-window GT merge:
- For T3-A (labs/imaging/micro), collect all corresponding events in (t, t+24h],
  produce gt_list=[{"value":..., "delta_hours":..., "weight":...}, ...]
  with exp decay weight where 0h->1.0, 24h->0.01.
"""

from __future__ import annotations

import argparse
import json
import math
import re
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
from collections import Counter, defaultdict

from tqdm import tqdm
from util.logUtil import setup_logger
logger = setup_logger()

# --------- LLM ----------
from util.llmUtil import LLMUtil
llm = LLMUtil()

def call_llm_json(prompt: str, system: str) -> Dict[str, Any]:
    return llm.chat_json(user_text=prompt, system_prompt=system)

# Optional (if you have it)
try:
    from EHR_pipeline.llm_tools import infer_imaging_modality_target_llm
except Exception:
    infer_imaging_modality_target_llm = None

# --------- constants ----------
ACTIONS = [
    "ask_question",
    "order_labs",
    "order_microbiology",
    "order_imaging",
    "perform_procedure",
    "medication",
    "discharge",
]

EVENT2ACTION = {
    "lab": "order_labs",
    "imaging": "order_imaging",
    "microbiology": "order_microbiology",
    "medication": "medication",
    "procedure": "perform_procedure"
}

# exp decay: 0h -> 1.0, 24h -> 0.01
_DECAY_K = math.log(100.0) / 24.0

def decay_weight(delta_hours: float) -> float:
    return float(math.exp(-_DECAY_K * max(0.0, delta_hours)))

def norm(s: str) -> str:
    return re.sub(r"\s+", " ", (s or "").strip())

def _norm_unit(u: str) -> str:
    u = norm(u)
    u = u.replace(" / ", "/").replace(" ", "")
    return u

def make_indicator_key(name: str, fluid: str, unit: str) -> str:
    name_n = norm(name)
    fluid_n = norm(fluid).title()
    unit_n = _norm_unit(unit)
    return f"{name_n}||{fluid_n}||{unit_n or 'NA'}"

def parse_time(ts: str) -> datetime:
    # e.g. "2160-03-23 10:00:00"
    return datetime.strptime(ts, "%Y-%m-%d %H:%M:%S")

def iter_json_files(root: Path):
    for p in root.rglob("*.json"):
        if p.name.startswith("."):
            continue
        yield p

# --------- context rendering ----------
def compact_event(ev: Dict[str, Any], max_items: int = 40) -> Dict[str, Any]:
    t = ev.get("type")
    out = {"type": t, "timestamp": ev.get("timestamp")}
    items = ev.get("items", []) or []
    if t == "lab":
        # keep just analytes summary
        out["items"] = [
            {
                "name": it.get("name"),
                "fluid": it.get("fluid"),
                "unit": it.get("unit") or it.get("units"),
                "flag": it.get("flag"),
            }
            for it in items[:max_items]
        ]
    elif t == "IMAGING":
        out["items"] = items[:min(max_items, len(items))]
    elif t == "microbiology":
        out["items"] = items[:min(max_items, len(items))]
    elif t == "MEDICATION":
        out["items"] = [
            {"drug": it.get("drug"), "route": it.get("route"), "dose": it.get("dose"), "status": it.get("status")}
            for it in items[:max_items]
        ]
    else:
        out["items"] = items[:min(max_items, len(items))]
    return out

def build_history(visit: Dict[str, Any], upto_time: datetime) -> List[Dict[str, Any]]:
    hist = []
    for ev in visit.get("event_stream", []) or []:
        ts = parse_time(ev["timestamp"])
        if ts <= upto_time:
            hist.append(compact_event(ev))
    return hist

# --------- GT extraction ----------
def gt_action_from_event(ev: Dict[str, Any]) -> Optional[str]:
    et = (ev.get("type") or "").lower()
    # normalize uppercase types in your sample: MEDICATION/IMAGING etc.
    if et in EVENT2ACTION:
        return EVENT2ACTION[et]
    if et == "medication":
        return "medication"
    if et == "imaging":
        return "order_imaging"
    if et == "microbiology":
        return "order_microbiology"
    if et == "lab":
        return "order_labs"
    return None

def infer_lab_panel_for_event(
    ev: Dict[str, Any],
    indicator_panel_map: Optional[Dict[str, str]],
) -> Tuple[Optional[str], Dict[str, Any]]:
    """
    Return:
      (panel_name, debug)
    panel_name inferred by voting over indicators in this lab event.
    """
    items = ev.get("items", []) or []
    if not items:
        return None, {"reason": "no_items"}

    if not indicator_panel_map:
        # fallback: let LLM infer a panel name for this whole event
        prompt = f"""
You are given a lab event containing multiple lab indicators.
Infer the most likely clinical test panel/order name for this event (open-set, no fixed enum).
Return JSON: {{"panel":"...","reason":"..."}}.

Lab indicators:
{json.dumps([{"name":it.get("name"),"fluid":it.get("fluid"),"unit":it.get("unit") or it.get("units")} for it in items[:60]], ensure_ascii=False)}
""".strip()
        out = call_llm_json(prompt, system="You are a clinical lab expert.")
        panel = norm(out.get("panel") or "")
        return (panel or None), {"llm": out}

    vote = Counter()
    used = 0
    miss = 0
    for it in items:
        name = norm(it.get("name") or "")
        fluid = norm(it.get("fluid") or "")
        unit = _norm_unit(it.get("unit") or it.get("units") or "")
        if not name:
            continue
        key = make_indicator_key(name, fluid, unit)
        p = indicator_panel_map.get(key)
        if p:
            vote[p] += 1
            used += 1
        else:
            miss += 1

    if not vote:
        return None, {"reason": "no_votes", "used": used, "miss": miss}

    panel, n = vote.most_common(1)[0]
    return panel, {"vote": dict(vote), "chosen": panel, "used": used, "miss": miss}

def infer_imaging_param_for_event(ev: Dict[str, Any], history_messages: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    """
    Return structured imaging label:
      {"modality": "...", "target": "..."}  # e.g. {"modality":"ct","target":"head"}
    Use your existing infer_imaging_modality_target_llm if available; else LLM on event items.
    """
    if infer_imaging_modality_target_llm is not None and history_messages is not None:
        try:
            # Your tool likely expects messages; adapt if needed.
            return infer_imaging_modality_target_llm(history_messages)
        except Exception:
            pass

    # fallback: infer from imaging items
    prompt = f"""
Infer imaging modality and body part target from this imaging event.
Return JSON only:
{{"modality":"ct|mri|xray|ultrasound|echo|doppler|pet|other","target":"free text body part"}}.

Imaging event:
{json.dumps(compact_event(ev), ensure_ascii=False)}
""".strip()
    out = call_llm_json(prompt, system="You are a radiology ordering expert.")
    return {
        "modality": norm(out.get("modality") or "other").lower(),
        "target": norm(out.get("target") or ""),
        "raw": out,
    }

def infer_micro_param_for_event(ev: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return {"specimen": "...", "test": "..."} open-set but suggest typical culture naming.
    """
    prompt = f"""
Infer microbiology order parameters from this microbiology event.
Return JSON only: {{"specimen":"...","test":"..."}}.

Event:
{json.dumps(compact_event(ev), ensure_ascii=False)}
""".strip()
    out = call_llm_json(prompt, system="You are a clinical microbiology expert.")
    return {"specimen": norm(out.get("specimen") or ""), "test": norm(out.get("test") or ""), "raw": out}

def infer_med_param_for_event(ev: Dict[str, Any]) -> Dict[str, Any]:
    """
    Return {"drug": "...", "dose": "..."}.
    If multiple meds in next event, GT can be list; for MCQ we usually pick 1 (most salient).
    We'll keep a list and let question builder pick.
    """
    meds = []
    for it in ev.get("items", []) or []:
        drug = norm(it.get("drug") or "")
        if not drug:
            continue
        meds.append(
            {
                "drug": drug,
                "dose": norm(it.get("dose") or ""),
                "route": norm(it.get("route") or ""),
                "status": norm(it.get("status") or ""),
            }
        )
    return {"meds": meds}

# --------- distractor generation ----------
def llm_generate_options(
    qtype: str,
    stem: str,
    gt: Any,
    history: List[Dict[str, Any]],
    n_options: int,
    forbid: List[str],
    preference_hint: str,
) -> List[Any]:
    """
    Return list of distractor options (length = n_options - 1 typically), excluding GT.
    "options" format depends on qtype:
      - T3-N: strings in ACTIONS
      - T3-A: strings (panels or imaging orders etc.)
      - T3-M: strings (drug names)
      - T3-D: "Yes"/"No"
    """
    prompt = f"""
You will generate multiple-choice distractor options for a clinical question.
Constraints:
- Distractors must be completely irrelevant to the ground-truth (GT) for the current decision.
- Do not output GT or near-synonyms of GT.
- Output JSON only.

Question type: {qtype}
Question stem: {stem}

Ground-truth (GT):
{json.dumps(gt, ensure_ascii=False)}

Preference hints (soft):
{preference_hint}

Forbidden options (hard):
{json.dumps(forbid, ensure_ascii=False)}

Patient history (events up to current time):
{json.dumps(history, ensure_ascii=False)}

Return JSON:
{{
  "options": ["opt1","opt2",...],
  "rationales": ["why opt1 is irrelevant", ...]
}}
Generate exactly {n_options} options.
""".strip()

    out = call_llm_json(prompt, system="You design adversarial-yet-plausible multiple-choice distractors for clinicians.")
    opts = out.get("options", []) or []
    cleaned = []
    seen = set()
    for x in opts:
        s = norm(str(x))
        if not s:
            continue
        if s in seen:
            continue
        if s in forbid:
            continue
        seen.add(s)
        cleaned.append(s)
        if len(cleaned) >= n_options:
            break
    return cleaned

# --------- question objects ----------
@dataclass
class Question:
    qid: str
    visit_id: str
    hadm_id: Any
    t_index: int
    timestamp: str
    qtype: str
    question: str
    options: List[Any]
    answer: Any
    meta: Dict[str, Any]

def make_qid(patient_id: str, visit_id: str, t_index: int, qtype: str, local_i: int) -> str:
    return f"{patient_id}-{visit_id}-T{t_index:04d}-{qtype}-{local_i}"

# --------- future-window gt list ----------
def collect_future_events(
    events: List[Dict[str, Any]],
    t0: datetime,
    horizon_h: float,
    match_action: str,
) -> List[Tuple[datetime, Dict[str, Any]]]:
    t1 = t0 + timedelta(hours=horizon_h)
    out = []
    for ev in events:
        ts = parse_time(ev["timestamp"])
        if ts <= t0:
            continue
        if ts > t1:
            continue
        act = gt_action_from_event(ev)
        if act == match_action:
            out.append((ts, ev))
    out.sort(key=lambda x: x[0])
    return out

# --------- builders ----------
def build_T3N(
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    gt_action: str,
    out_options_k: int,
) -> Question:
    history = build_history(visit, t_cur)
    stem = "Next step is most appropriate?"

    # preference hints per your spec
    hint = ""
    if gt_action == "order_imaging":
        hint = "Prefer distractors: order_labs, ask_question (typical clinical pathway)."
    elif gt_action == "medication":
        hint = "Prefer distractors: order_labs (recheck), perform_procedure (more aggressive)."
    elif gt_action == "discharge":
        hint = "Prefer distractors: medication (adjust), order_labs (recheck)."

    forbid = [gt_action]
    # Ask LLM to pick k-1 distractors from ACTIONS, irrelevant to GT.
    # We still enforce it's from ACTIONS by post-filtering.
    llm_opts = llm_generate_options(
        qtype="T3-N",
        stem=stem,
        gt={"action": gt_action},
        history=history,
        n_options=max(6, out_options_k),  # ask a few more, then filter
        forbid=forbid,
        preference_hint=hint,
    )
    # filter to allowed actions
    distractors = []
    for x in llm_opts:
        if x in ACTIONS and x != gt_action:
            distractors.append(x)
    # backfill deterministically if insufficient
    for a in ACTIONS:
        if a != gt_action and a not in distractors:
            distractors.append(a)
        if len(distractors) >= out_options_k - 1:
            break

    options = distractors[: out_options_k - 1] + [gt_action]
    # shuffle but keep deterministic-ish: put GT random? here keep last to simplify
    q = Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-N", 0),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-N",
        question=stem,
        options=options,
        answer=gt_action,
        meta={"history": history, "gt_action": gt_action},
    )
    return q

def build_T3A_labs(
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    indicator_panel_map: Optional[Dict[str, str]],
    out_options_k: int,
) -> Optional[Question]:
    # merge all lab events within 24h after current time (including next)
    future = collect_future_events(events, t_cur, 24.0, "order_labs")
    if not future:
        return None

    gt_list = []
    chosen_panel = None
    debug_list = []

    for ts, ev in future:
        panel, dbg = infer_lab_panel_for_event(ev, indicator_panel_map)
        debug_list.append({"timestamp": ev["timestamp"], "panel": panel, "debug": dbg})
        if not panel:
            continue
        dh = (ts - t_cur).total_seconds() / 3600.0
        gt_list.append({"value": panel, "delta_hours": dh, "weight": decay_weight(dh)})

    if not gt_list:
        return None

    # main GT: earliest panel
    chosen_panel = gt_list[0]["value"]
    history = build_history(visit, t_cur)
    stem = "Which lab panel/order is most appropriate next?"

    # LLM generate irrelevant panel names
    forbid = list({chosen_panel})
    hint = "Generate common but irrelevant lab orders/panels that do NOT match GT."

    distractors = llm_generate_options(
        qtype="T3-A-labs",
        stem=stem,
        gt={"panel": chosen_panel, "gt_list": gt_list},
        history=history,
        n_options=out_options_k - 1,
        forbid=forbid,
        preference_hint=hint,
    )
    # backfill with generic negatives if needed
    while len(distractors) < out_options_k - 1:
        distractors.append(f"Unrelated Lab Order {len(distractors)+1}")

    options = distractors[: out_options_k - 1] + [chosen_panel]

    return Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-A", 0),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-A",
        question=stem,
        options=options,
        answer=chosen_panel,  # evaluation should use gt_list + topk/decay; answer is "primary"
        meta={
            "subtype": "labs",
            "history": history,
            "gt_list": gt_list,
            "gt_primary": chosen_panel,
            "debug": debug_list,
        },
    )

def build_T3A_imaging(
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    out_options_k: int,
) -> Optional[Question]:
    future = collect_future_events(events, t_cur, 24.0, "order_imaging")
    if not future:
        return None

    history = build_history(visit, t_cur)

    gt_list = []
    debug = []
    for ts, ev in future:
        lab = infer_imaging_param_for_event(ev, history_messages=None)
        # normalize to a single string option
        modality = norm(lab.get("modality") or "other").lower()
        target = norm(lab.get("target") or "")
        value = f"{modality.upper()} {target}".strip()
        dh = (ts - t_cur).total_seconds() / 3600.0
        gt_list.append({"value": value, "delta_hours": dh, "weight": decay_weight(dh)})
        debug.append({"timestamp": ev["timestamp"], "parsed": lab})

    if not gt_list:
        return None

    chosen = gt_list[0]["value"]
    stem = "Which imaging order is most appropriate next?"
    forbid = [chosen]
    hint = "Generate imaging orders that are irrelevant to GT. Prefer same body part different modality, or same modality different body part."

    distractors = llm_generate_options(
        qtype="T3-A-imaging",
        stem=stem,
        gt={"imaging": chosen, "gt_list": gt_list},
        history=history,
        n_options=out_options_k - 1,
        forbid=forbid,
        preference_hint=hint,
    )
    while len(distractors) < out_options_k - 1:
        distractors.append(f"XR Unrelated Part {len(distractors)+1}")

    options = distractors[: out_options_k - 1] + [chosen]

    return Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-A", 1),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-A",
        question=stem,
        options=options,
        answer=chosen,
        meta={"subtype": "imaging", "history": history, "gt_list": gt_list, "gt_primary": chosen, "debug": debug},
    )

def build_T3A_micro(
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    out_options_k: int,
) -> Optional[Question]:
    future = collect_future_events(events, t_cur, 24.0, "order_microbiology")
    if not future:
        return None

    history = build_history(visit, t_cur)

    gt_list = []
    debug = []
    for ts, ev in future:
        p = infer_micro_param_for_event(ev)
        specimen = norm(p.get("specimen") or "")
        test = norm(p.get("test") or "culture")
        value = f"{specimen} {test}".strip()
        dh = (ts - t_cur).total_seconds() / 3600.0
        gt_list.append({"value": value, "delta_hours": dh, "weight": decay_weight(dh)})
        debug.append({"timestamp": ev["timestamp"], "parsed": p})

    if not gt_list:
        return None

    chosen = gt_list[0]["value"]
    stem = "Which microbiology test is most appropriate next?"
    forbid = [chosen]
    hint = "Generate common but irrelevant cultures by swapping specimen (blood vs urine vs sputum) or unrelated tests."

    distractors = llm_generate_options(
        qtype="T3-A-micro",
        stem=stem,
        gt={"micro": chosen, "gt_list": gt_list},
        history=history,
        n_options=out_options_k - 1,
        forbid=forbid,
        preference_hint=hint,
    )
    while len(distractors) < out_options_k - 1:
        distractors.append(f"Urine culture (irrelevant) {len(distractors)+1}")

    options = distractors[: out_options_k - 1] + [chosen]

    return Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-A", 2),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-A",
        question=stem,
        options=options,
        answer=chosen,
        meta={"subtype": "micro", "history": history, "gt_list": gt_list, "gt_primary": chosen, "debug": debug},
    )

def build_T3M_medication(
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    out_options_k: int,
) -> Optional[Question]:
    future = collect_future_events(events, t_cur, 24.0, "medication")
    if not future:
        return None

    history = build_history(visit, t_cur)

    # choose earliest med in earliest medication event as primary GT
    ts0, ev0 = future[0]
    mp = infer_med_param_for_event(ev0)
    meds = mp.get("meds", []) or []
    if not meds:
        return None

    primary_drug = meds[0]["drug"]
    # GT list can include multiple meds in 24h window (topk evaluation)
    gt_list = []
    debug = []
    for ts, ev in future:
        mp2 = infer_med_param_for_event(ev)
        for m in mp2.get("meds", []) or []:
            dh = (ts - t_cur).total_seconds() / 3600.0
            gt_list.append({"value": m["drug"], "delta_hours": dh, "weight": decay_weight(dh)})
        debug.append({"timestamp": ev["timestamp"], "meds": mp2.get("meds", [])})

    stem = "Which medication is most appropriate next?"
    forbid = [primary_drug]
    hint = "Generate medications that are plausible but irrelevant to the current GT and history. Avoid near-duplicate drug names."

    distractors = llm_generate_options(
        qtype="T3-M",
        stem=stem,
        gt={"drug": primary_drug, "gt_list": gt_list},
        history=history,
        n_options=out_options_k - 1,
        forbid=forbid,
        preference_hint=hint,
    )
    while len(distractors) < out_options_k - 1:
        distractors.append(f"Unrelated Drug {len(distractors)+1}")

    options = distractors[: out_options_k - 1] + [primary_drug]

    return Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-M", 0),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-M",
        question=stem,
        options=options,
        answer=primary_drug,
        meta={"history": history, "gt_list": gt_list, "gt_primary": primary_drug, "debug": debug},
    )

def build_T3D_discharge(
    patient_id: str,
    visit: Dict[str, Any],
    events: List[Dict[str, Any]],
    t_index: int,
    t_cur: datetime,
    discharge_time: Optional[datetime],
    X_hours: float,
    out_options_k: int = 2,
) -> Optional[Question]:
    if discharge_time is None:
        return None
    # label: Yes if discharge within X hours after t_cur
    yes = (discharge_time - t_cur).total_seconds() / 3600.0 <= X_hours
    gt = "Yes" if yes else "No"

    history = build_history(visit, t_cur)
    stem = f"Should the patient be discharged now? (GT rule: discharge within {X_hours:.0f}h => Yes)"

    options = ["Yes", "No"]
    return Question(
        qid=make_qid(patient_id, visit["visit_id"], t_index, "T3-D", 0),
        visit_id=visit["visit_id"],
        hadm_id=visit.get("hadm_id"),
        t_index=t_index,
        timestamp=events[t_index]["timestamp"],
        qtype="T3-D",
        question=stem,
        options=options,
        answer=gt,
        meta={"history": history, "discharge_time": discharge_time.strftime("%Y-%m-%d %H:%M:%S"), "X_hours": X_hours},
    )

# --------- main pipeline ----------

import random

def sample_decision_points(events: List[Dict[str, Any]], n_points: int, seed: int, visit_key: str) -> List[int]:
    """
    Sample n_points indices i as decision points in this visit.
    Constraint: i must allow GT = events[i+1], so i in [0, len(events)-2].
    We also avoid picking indices where next event cannot be mapped to GT action.
    """
    if len(events) < 2:
        return []

    # deterministic RNG per visit
    rng = random.Random(f"{seed}::{visit_key}")

    candidates = []
    for i in range(len(events) - 1):
        nxt = events[i + 1]
        if gt_action_from_event(nxt):
            candidates.append(i)

    if not candidates:
        return []

    if len(candidates) <= n_points:
        return sorted(candidates)

    return sorted(rng.sample(candidates, k=n_points))

def generate_questions_for_visit(
    patient_id: str,
    visit: Dict[str, Any],
    indicator_panel_map: Optional[Dict[str, str]],
    k_action: int,
    k_param: int,
    k_med: int,
    enable_discharge_q: bool,
    discharge_Xh: float,
    discharge_only_within_h: float,
    seed: int = 42,
) -> List[Dict[str, Any]]:
    events = list(visit.get("event_stream", []) or [])
    if len(events) < 2:
        return []

    # sort by timestamp
    events.sort(key=lambda e: parse_time(e["timestamp"]))

    discharge_time = None
    try:
        dt = visit.get("discharge_info", {}).get("discharge_time")
        if dt:
            discharge_time = parse_time(dt)
    except Exception:
        discharge_time = None

    out: List[Question] = []

    # ---- sample 2 decision points per visit ----
    visit_key = f"{patient_id}::{visit.get('visit_id')}::{visit.get('hadm_id')}"
    decision_points = sample_decision_points(events, n_points=2, seed=seed, visit_key=visit_key)
    logger.info(f"Visit {visit_key}: sampled decision points at indices {decision_points} / {len(events)-1}")
    
    for i in decision_points:
        cur = events[i]
        nxt = events[i + 1]
        t_cur = parse_time(cur["timestamp"])

        gt_act = gt_action_from_event(nxt)
        if not gt_act:
            continue

        # ---- T3-N (always) ----
        out.append(build_T3N(patient_id, visit, events, i, t_cur, gt_act, k_action))

        # ---- 1 extra question max by default (param or med). You can allow 2 if you want. ----
        if gt_act == "order_labs":
            q = build_T3A_labs(patient_id, visit, events, i, t_cur, indicator_panel_map, k_param)
            if q: out.append(q)
        elif gt_act == "order_imaging":
            q = build_T3A_imaging(patient_id, visit, events, i, t_cur, k_param)
            if q: out.append(q)
        elif gt_act == "order_microbiology":
            q = build_T3A_micro(patient_id, visit, events, i, t_cur, k_param)
            if q: out.append(q)
        elif gt_act == "medication":
            q = build_T3M_medication(patient_id, visit, events, i, t_cur, k_med)
            if q: out.append(q)

        # ---- T3-D near discharge ----
        if enable_discharge_q and discharge_time is not None:
            # only ask within some window before discharge to reduce redundancy
            hrs_to_discharge = (discharge_time - t_cur).total_seconds() / 3600.0
            if 0.0 <= hrs_to_discharge <= discharge_only_within_h:
                qd = build_T3D_discharge(
                    patient_id, visit, events, i, t_cur, discharge_time, discharge_Xh, out_options_k=2
                )
                if qd:
                    out.append(qd)

    # serialize
    return [q.__dict__ for q in out]

def load_indicator_panel_map(path: Optional[str]) -> Optional[Dict[str, str]]:
    if not path:
        return None
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(p)
    return json.loads(p.read_text(encoding="utf-8"))

def write_questions_jsonl(patient_out_path: Path, questions: List[Dict[str, Any]]) -> int:
    if not questions:
        return 0
    patient_out_path.parent.mkdir(parents=True, exist_ok=True)
    with patient_out_path.open("a", encoding="utf-8") as fw:
        for q in questions:
            fw.write(json.dumps(q, ensure_ascii=False) + "\n")
    return len(questions)


def main():
    from config import AgentQaGenConfig
    
    cfg = AgentQaGenConfig()

    in_dir = cfg.INPUT_DIR
    out_path = cfg.OUTPUT_PATH
    out_path.parent.mkdir(parents=True, exist_ok=True)

    indicator_panel_map = load_indicator_panel_map(cfg.INDICATOR_PANEL_MAP)
    total_q = 0
    total_patients = 0

    for fp in tqdm(list(iter_json_files(in_dir)), desc="Generating per-patient jsonl"):
        obj = json.loads(fp.read_text(encoding="utf-8"))
        patient_id = obj.get("patient_info", {}).get("patient_id") or fp.stem

        patient_out = out_path / f"{patient_id}.jsonl"
        wrote_any = False

        for visit in obj.get("visits", []) or []:
            qs = generate_questions_for_visit(
                patient_id=patient_id,
                visit=visit,
                indicator_panel_map=indicator_panel_map,
                k_action=cfg.K_ACTION,
                k_param=cfg.K_PARAM,
                k_med=cfg.K_MED,
                enable_discharge_q=cfg.ENABLE_DISCHARGE_Q,
                discharge_Xh=cfg.DISCHARGE_XH,
                discharge_only_within_h=cfg.DISCHARGE_ONLY_WITHIN_H,
                seed=cfg.RANDOM_SEED,
            )
            n = write_questions_jsonl(patient_out, qs)
            if n > 0:
                wrote_any = True
                total_q += n

        if wrote_any:
            total_patients += 1
            
        if cfg.DEMO_MODE:
            if total_patients >= cfg.DEMO_N:  
                break

    logger.success(f"Wrote {total_q} questions for {total_patients} patients into folder: {out_path}")

if __name__ == "__main__":
    main()
